-- Signature skill catalog: families, discovery, action progress, hidden skills, and ultimates.

CREATE TABLE skill_families (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  family_key VARCHAR(80) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  symbol VARCHAR(20) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  identity_theme VARCHAR(255) NOT NULL,
  progression_rules_json JSON NOT NULL
);

ALTER TABLE skills
  ADD COLUMN family_id BIGINT UNSIGNED NULL AFTER skill_key,
  ADD COLUMN category VARCHAR(80) NOT NULL DEFAULT 'General' AFTER skill_type,
  ADD COLUMN rarity ENUM('common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic') NOT NULL DEFAULT 'common' AFTER category,
  ADD COLUMN visibility ENUM('normal', 'secret', 'hidden') NOT NULL DEFAULT 'normal' AFTER rarity,
  ADD COLUMN family_tier INT NOT NULL DEFAULT 1 AFTER visibility,
  ADD COLUMN identity_text TEXT NULL AFTER description,
  ADD COLUMN unlock_hint TEXT NULL AFTER identity_text,
  ADD COLUMN discovery_rules_json JSON NULL AFTER requirements_json,
  ADD COLUMN evolution_rules_json JSON NULL AFTER discovery_rules_json,
  ADD CONSTRAINT fk_skills_family FOREIGN KEY (family_id) REFERENCES skill_families(id) ON DELETE SET NULL;

ALTER TABLE character_skills
  ADD COLUMN discovered_at TIMESTAMP NULL AFTER unlocked,
  ADD COLUMN discovery_context_json JSON NULL AFTER discovered_at;

CREATE TABLE skill_progress_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  character_life_id BIGINT UNSIGNED NOT NULL,
  skill_id BIGINT UNSIGNED NOT NULL,
  story_cycle_id BIGINT UNSIGNED NOT NULL,
  action_text TEXT NOT NULL,
  action_signature VARCHAR(160) NOT NULL,
  success_level ENUM('failed', 'partial', 'success', 'exceptional') NOT NULL,
  progress_amount INT NOT NULL DEFAULT 0,
  evidence_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_skill_progress_character_skill (character_life_id, skill_id, created_at),
  CONSTRAINT fk_skill_progress_life FOREIGN KEY (character_life_id) REFERENCES character_lives(id) ON DELETE CASCADE,
  CONSTRAINT fk_skill_progress_skill FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE,
  CONSTRAINT fk_skill_progress_cycle FOREIGN KEY (story_cycle_id) REFERENCES story_cycles(id) ON DELETE CASCADE
);

INSERT INTO skill_families (id, family_key, name, symbol, description, identity_theme, progression_rules_json) VALUES
(1, 'predator', 'Predator Family', 'FANG', 'Abilities earned by hunting, consuming, analyzing, and adapting to worthy prey.', 'Hunger becomes understanding, then evolution.', '{"coreActions":["defeat","consume","analyze","adapt"],"ultimateRequiresFamilyMastery":true}'),
(2, 'dragon', 'Dragon Family', 'SCALE', 'Draconic breath, scales, fear, and sovereign elemental power.', 'The body remembers an age when dragons ruled the sky.', '{"coreActions":["endure_element","roar","protect_territory","defeat_dragon"],"ultimateRequiresFamilyMastery":true}'),
(3, 'shadow', 'Shadow Family', 'SHADE', 'Movement, binding, duplication, and control through living darkness.', 'A second self walks wherever light refuses to remain.', '{"coreActions":["hide","ambush","bind","move_unseen"],"ultimateRequiresFamilyMastery":true}'),
(4, 'arcane', 'Arcane Family', 'RUNE', 'Mana recovery, shaping, analysis, and the creation of spell structures.', 'Magic is not borrowed. It is engineered.', '{"coreActions":["study_magic","shape_mana","create_tool","solve_spell"],"ultimateRequiresFamilyMastery":true}'),
(5, 'monarch', 'Monarch Family', 'CROWN', 'Authority, command, presence, and power recognized by the world itself.', 'The world hesitates because it recognizes a ruler.', '{"coreActions":["lead","command","accept_responsibility","inspire_loyalty"],"ultimateRequiresFamilyMastery":true}'),
(6, 'soul', 'Soul Family', 'SOUL', 'Abilities tied to memory, reincarnation, will, spirits, and the immortal self.', 'The body dies. The soul continues learning.', '{"coreActions":["remember","resist_death","interact_with_soul","reincarnate"],"ultimateRequiresFamilyMastery":true}');

INSERT INTO skills (skill_key, family_id, name, skill_type, category, rarity, visibility, family_tier, description, identity_text, unlock_hint, effects_json, requirements_json, discovery_rules_json, evolution_rules_json) VALUES
('predator', 1, 'Predator', 'active', 'Soul', 'rare', 'secret', 2, 'Devour a defeated enemy to absorb fragments of ability or memory.', 'The defeated creature does not disappear. Part of it wakes inside you.', 'Learn what remains after a worthy enemy dies.', '{"consumeDefeatedTarget":true,"possibleRewards":["memory_fragment","trait_progress","skill_progress"]}', '{"targetStatus":"defeated","targetHasAbsorbableFragment":true}', '{"actions":["consume_defeated_enemy"],"successfulUses":3,"requiresAnalysis":true}', '{"nextSkills":["absolute-predator","beelzar-king-of-consumption"]}'),
('abyss-gaze', 1, 'Abyss Gaze', 'passive', 'Perception', 'rare', 'secret', 2, 'Reveal hidden creatures, traps, weak points, and magical traces.', 'Your eyes stop searching the world and begin searching what the world conceals.', 'Survive dangers that ordinary sight could not reveal.', '{"reveals":["hidden_creature","trap","weak_point","magic_trace"]}', '{"perception":8}', '{"successfulHiddenDiscoveries":10,"surviveAmbushes":3}', '{"nextSkills":["absolute-predator"]}'),
('soul-devour', 6, 'Soul Devour', 'active', 'Soul', 'epic', 'secret', 3, 'Consume a fragment of a defeated soul to restore energy and strengthen Soul Rank.', 'A second heartbeat vanishes, and your immortal soul grows heavier.', 'Predator must learn the difference between flesh and soul.', '{"restoreSoulEnergy":true,"soulRankProgress":true}', '{"skills":["predator"],"soulLevel":3}', '{"soulFragmentsConsumed":5,"mercyConsequenceTracked":true}', '{"nextSkills":["azrael-lord-of-souls","beelzar-king-of-consumption"]}'),
('blood-fang', 1, 'Blood Fang', 'active', 'Physical', 'uncommon', 'normal', 1, 'A crushing bite that restores health from damage dealt.', 'Instinct takes the shape of fangs before thought can object.', 'Survive by biting when no weapon remains.', '{"damageType":"physical","lifeStealPercent":20}', '{"bodyCanBite":true}', '{"successfulBites":5,"lowHealthUses":2}', '{"nextSkills":["predator"]}'),
('void-step', 3, 'Void Step', 'active', 'Movement', 'epic', 'secret', 3, 'Move a short distance by stepping through the Void.', 'For one breath, distance forgets that it exists.', 'Cross a space that cannot be crossed normally.', '{"shortTeleport":true,"staminaCost":12}', '{"agility":10,"resolve":8}', '{"impossibleDodges":3,"shadowStepMastery":true}', '{"nextSkills":["dimensional-rift","void-dominion"]}'),
('shadow-thread', 3, 'Shadow Thread', 'active', 'Dark', 'rare', 'normal', 2, 'Create dark threads that bind or manipulate enemies.', 'Your shadow unravels into patient black fingers.', 'Use darkness to restrain instead of merely hide.', '{"bind":true,"manipulateObjects":true,"manaCost":8}', '{"thaumaturgy":7}', '{"creativeShadowBindings":5}', '{"nextSkills":["shadow-clone","eclipse-monarch"]}'),
('predator-instinct', 1, 'Predator Instinct', 'passive', 'Perception', 'rare', 'secret', 2, 'Sense immediate danger before an ambush begins.', 'The body moves before the mind understands why.', 'Survive repeated ambushes by trusting instinct.', '{"ambushWarning":true}', '{"resolve":6}', '{"ambushesSurvived":5,"firstReactionSuccesses":3}', '{"nextSkills":["abyss-gaze"]}'),
('mana-core', 4, 'Mana Core', 'passive', 'Arcane', 'rare', 'normal', 2, 'Greatly increase natural mana recovery.', 'Mana stops passing through you and begins orbiting a new inner star.', 'Exhaust your mana, recover, and understand its natural rhythm.', '{"manaRecoveryMultiplier":1.75}', '{"thaumaturgy":8}', '{"manaExhaustionsSurvived":3,"meditationSuccesses":8}', '{"nextSkills":["arcane-creation","origin-magic"]}'),
('evolution', 1, 'Evolution', 'active', 'Soul', 'legendary', 'secret', 4, 'Evolve the current body after meeting exceptional biological and soul conditions.', 'The body asks the soul what it must become to survive the next dawn.', 'Adapt beyond the limits of your current species.', '{"bodyEvolution":true,"permanentTransformation":true}', '{"familyMastery":"predator","soulEnergy":500}', '{"absorbedTraits":5,"nearDeathAdaptations":3,"specialEventRequired":true}', '{"nextSkills":["divine-evolution","absolute-predator"]}'),
('analyze', 4, 'Analyze', 'active', 'Support', 'uncommon', 'normal', 1, 'Examine a target to reveal statistics, weaknesses, resistances, and possible loot.', 'Facts arrange themselves into a quiet answer behind your eyes.', 'Study enemies before choosing violence.', '{"reveals":["stats","weaknesses","resistances","loot"]}', '{"intelligence":6}', '{"targetsStudied":5,"correctPredictions":3}', '{"nextSkills":["parallel-mind","abyss-gaze"]}'),
('parallel-mind', 4, 'Parallel Mind', 'passive', 'Soul', 'epic', 'secret', 3, 'Create an additional thought process for analysis or spellcasting.', 'A second voice answers from inside your own thought, calm and already working.', 'Complete two complex mental tasks under lethal pressure.', '{"parallelAnalysis":true,"spellPreparationBonus":true}', '{"skills":["analyze"],"intelligence":12}', '{"simultaneousTasks":10,"mentalOverloadSurvived":2}', '{"nextSkills":["world-rewrite","origin-magic"]}'),
('demon-eye', NULL, 'Demon Eye', 'passive', 'Perception', 'epic', 'secret', 3, 'Detect lies, illusions, curses, and hidden magic.', 'A forbidden pupil opens where doubt used to live.', 'See through a lie that deceived an entire realm.', '{"detects":["lie","illusion","curse","hidden_magic"]}', '{"resolve":9,"thaumaturgy":8}', '{"majorIllusionsBroken":3,"cursesSurvived":2}', '{"nextSkills":["abyss-gaze"]}'),
('black-flame', NULL, 'Black Flame', 'active', 'Fire/Dark', 'epic', 'normal', 3, 'Summon cursed flames that continue burning after impact.', 'The flame gives no warmth. It burns promises before flesh.', 'Combine fire with a curse without losing control.', '{"damageTypes":["fire","dark"],"persistentBurn":true,"manaCost":18}', '{"thaumaturgy":11,"resolve":8}', '{"cursedFireControlled":5}', '{"nextSkills":["eclipse-monarch"]}'),
('soul-chain', 6, 'Soul Chain', 'active', 'Spirit', 'epic', 'secret', 3, 'Bind an enemy soul and reduce escape or regeneration.', 'A chain appears in the space between two heartbeats.', 'Prevent a spirit from escaping without destroying it.', '{"bindSoul":true,"blocksEscape":true,"reducesRegeneration":true}', '{"soulLevel":4,"resolve":10}', '{"spiritsBound":5,"soulsReleasedMercifully":1}', '{"nextSkills":["azrael-lord-of-souls"]}'),
('dragon-breath', 2, 'Dragon Breath', 'active', 'Dragon', 'epic', 'normal', 3, 'Release a destructive breath attack based on the current element.', 'Your lungs remember a shape too vast for your body.', 'Carry a dragon fragment and survive its elemental awakening.', '{"elementUsesCurrentAffinity":true,"areaAttack":true}', '{"dragonTrait":true}', '{"dragonFragmentAwakened":true,"elementalDamageSurvived":5}', '{"nextSkills":["dragon-emperor"]}'),
('regeneration', 1, 'Regeneration', 'passive', 'Body', 'rare', 'normal', 2, 'Gradually restore lost health over time.', 'The wound closes as if the body refuses to remember being broken.', 'Recover from severe wounds without ordinary healing.', '{"healthRecoveryOverTime":true}', '{"resolve":8}', '{"naturalRecoveries":10,"majorInjuriesSurvived":2}', '{"nextSkills":["adaptive-body","divine-evolution"]}'),
('absolute-focus', 6, 'Absolute Focus', 'active', 'Mind', 'rare', 'normal', 2, 'Temporarily ignore fear, confusion, and mental interference.', 'The world becomes one decision wide.', 'Choose a clear action while fear and confusion are both active.', '{"immunities":["fear","confused","mental_interference"],"durationTurns":3}', '{"resolve":10}', '{"mentalEffectsResisted":8}', '{"nextSkills":["endless-will"]}'),
('spatial-storage', 4, 'Spatial Storage', 'active', 'Utility', 'epic', 'secret', 3, 'Store items inside a personal dimensional space.', 'A silent room opens where no direction points.', 'Preserve an item while every physical container is destroyed.', '{"dimensionalInventory":true}', '{"thaumaturgy":10,"intelligence":9}', '{"spaceMagicEvents":3,"rareRelicRequired":true}', '{"nextSkills":["dimensional-rift","infinite-arsenal"]}'),
('arcane-creation', 4, 'Arcane Creation', 'active', 'Magic', 'rare', 'normal', 2, 'Shape raw mana into simple temporary weapons or tools.', 'Thought gives mana an edge, a handle, and a purpose.', 'Solve practical problems by shaping mana instead of casting attacks.', '{"createTemporaryTool":true,"manaCostByComplexity":true}', '{"skills":["mana-core"],"intelligence":8}', '{"manaToolsCreated":10,"uniqueToolPurposes":5}', '{"nextSkills":["infinite-arsenal","origin-magic"]}'),
('endless-will', 6, 'Endless Will', 'reaction', 'Soul', 'legendary', 'hidden', 4, 'Refuse death once under special conditions and survive with one health.', 'Death arrives. Your soul answers: not this time.', NULL, '{"surviveLethalDamage":true,"remainingHp":1,"oncePerLife":true}', '{"resolve":15,"soulLevel":5}', '{"protectingSomeone":true,"lethalEvent":true,"unusedThisLife":true}', '{"nextSkills":["eternal-reincarnation","azrael-lord-of-souls"]}');

INSERT INTO skills (skill_key, family_id, name, skill_type, category, rarity, visibility, family_tier, description, identity_text, unlock_hint, effects_json, requirements_json, discovery_rules_json, evolution_rules_json) VALUES
('devour', 1, 'Devour', 'active', 'Physical/Soul', 'uncommon', 'normal', 1, 'Consume suitable defeated matter to recover and gain adaptation progress.', 'Hunger becomes a tool rather than an instinct.', 'Consume what defeated you would have used to survive.', '{"restoreStamina":true,"adaptationProgress":true}', '{"targetStatus":"defeated"}', '{"successfulConsumes":3}', '{"nextSkills":["predator"]}'),
('adaptive-body', 1, 'Adaptive Body', 'passive', 'Body', 'epic', 'secret', 3, 'Develop resistance after repeatedly surviving the same danger.', 'Pain leaves instructions behind.', 'Survive the same damage type until the body learns.', '{"adaptiveResistance":true}', '{"skills":["regeneration"]}', '{"sameDamageTypeSurvived":10}', '{"nextSkills":["evolution"]}'),
('dragon-scales', 2, 'Dragon Scales', 'reaction', 'Dragon', 'rare', 'normal', 2, 'Manifest temporary scales against overwhelming damage.', 'Light catches on armor that was not there a heartbeat ago.', 'Protect something while enduring elemental force.', '{"temporaryDefense":true,"elementalResistance":true}', '{"dragonTrait":true}', '{"elementalBlocks":5}', '{"nextSkills":["dragon-emperor"]}'),
('dragon-fear', 2, 'Dragon Fear', 'active', 'Dragon', 'epic', 'secret', 3, 'Project draconic presence that breaks weak resolve.', 'Every smaller instinct remembers the shape of a dragon.', 'Make a stronger predator hesitate without attacking.', '{"fearAura":true}', '{"dragonTrait":true,"charisma":10}', '{"predatorsIntimidated":5}', '{"nextSkills":["dragon-emperor"]}'),
('shadow-step', 3, 'Shadow Step', 'active', 'Movement', 'rare', 'normal', 2, 'Move rapidly between connected shadows.', 'Your foot lands where your shadow arrived first.', 'Escape danger by treating darkness as a path.', '{"shadowMovement":true,"staminaCost":8}', '{"agility":8}', '{"shadowEscapes":5}', '{"nextSkills":["void-step"]}'),
('shadow-clone', 3, 'Shadow Clone', 'active', 'Dark', 'epic', 'secret', 3, 'Create a short-lived duplicate from condensed shadow.', 'The shadow stands up and chooses a different enemy.', 'Make your shadow perform an action independently.', '{"temporaryDuplicate":true,"manaCost":16}', '{"skills":["shadow-thread"],"thaumaturgy":10}', '{"shadowManipulations":10}', '{"nextSkills":["eclipse-monarch"]}'),
('mana-burst', 4, 'Mana Burst', 'reaction', 'Arcane', 'rare', 'normal', 2, 'Release compressed mana in every direction during immediate danger.', 'The Mana Core beats once, and the room moves away from you.', 'Overload your Mana Core to survive being surrounded.', '{"areaKnockback":true,"manaCost":20}', '{"skills":["mana-core"]}', '{"surroundedEscapes":3}', '{"nextSkills":["ragnarok-drive"]}'),
('royal-decree', 5, 'Royal Decree', 'active', 'Monarch', 'epic', 'secret', 3, 'Issue a command strengthened by earned loyalty and authority.', 'The command carries the weight of everyone who chose to follow you.', 'Lead others through a crisis without demanding obedience.', '{"commandInfluence":true}', '{"charisma":12,"loyalCompanions":2}', '{"leadershipSuccesses":10}', '{"nextSkills":["monarchs-authority","celestial-throne"]}'),
('absolute-presence', 5, 'Absolute Presence', 'passive', 'Monarch', 'legendary', 'hidden', 4, 'Your arrival changes the morale and attention of everyone present.', 'The room recognizes you before anyone turns to look.', NULL, '{"moraleAura":true,"suppressesWeakHostility":true}', '{"skills":["royal-decree"],"charisma":16}', '{"realmsLed":3,"majorFactionsRecognizePlayer":3}', '{"nextSkills":["celestial-throne","eclipse-monarch"]}'),
('reincarnation-instinct', 6, 'Reincarnation Instinct', 'passive', 'Soul', 'rare', 'secret', 2, 'React to dangers remembered by previous bodies.', 'A dead body remembers the mistake before this body repeats it.', 'Face the cause of a previous death in a new body.', '{"pastLifeDangerWarning":true}', '{"totalDeaths":1}', '{"previousDeathPatternEncountered":true}', '{"nextSkills":["soul-archive","eternal-reincarnation"]}');

-- Hidden skills never appear in normal catalogs or ordinary unlock previews.
INSERT INTO skills (skill_key, family_id, name, skill_type, category, rarity, visibility, family_tier, description, identity_text, unlock_hint, effects_json, requirements_json, discovery_rules_json, evolution_rules_json) VALUES
('monarchs-authority', 5, 'Monarch''s Authority', 'active', 'Monarch', 'mythic', 'hidden', 5, 'Impose earned authority on the battlefield and world around you.', 'Reality listens because countless wills already chose to.', NULL, '{"authorityField":true}', '{"familyMastery":"monarch"}', '{"impossibleAchievement":"unite_hostile_realms"}', '{"nextSkills":["celestial-throne"]}'),
('time-fracture', NULL, 'Time Fracture', 'active', 'Time', 'mythic', 'hidden', 5, 'Break one moment into multiple possible actions.', 'The second hand cracks, and unfinished choices spill out.', NULL, '{"extraMoment":true}', '{"soulLevel":10}', '{"impossibleAchievement":"act_between_frozen_moments"}', '{"nextSkills":["world-rewrite"]}'),
('world-rewrite', 4, 'World Rewrite', 'ultimate', 'Origin', 'mythic', 'hidden', 6, 'Rewrite one local rule of reality at an immense permanent cost.', 'A sentence appears beneath the world, waiting for one word to change.', NULL, '{"rewriteLocalRule":true,"permanentCost":true}', '{"skills":["parallel-mind","origin-magic"]}', '{"impossibleAchievement":"discover_world_source_sentence"}', NULL),
('absolute-predator', 1, 'Absolute Predator', 'ultimate', 'Predator', 'mythic', 'hidden', 6, 'Analyze, consume, and perfectly adapt to one worthy defeated target.', 'Nothing remains outside your understanding except the price.', NULL, '{"perfectAbsorption":true}', '{"familyMastery":"predator","skills":["predator","evolution","abyss-gaze"]}', '{"impossibleAchievement":"defeat_and_understand_apex_self"}', NULL),
('void-dominion', 3, 'Void Dominion', 'ultimate', 'Void', 'mythic', 'hidden', 6, 'Claim a bounded region of Void as personal territory.', 'Direction, distance, and escape become permissions only you can grant.', NULL, '{"voidTerritory":true}', '{"skills":["void-step","dimensional-rift"]}', '{"impossibleAchievement":"survive_outside_reality"}', NULL),
('divine-evolution', 1, 'Divine Evolution', 'ultimate', 'Soul', 'mythic', 'hidden', 6, 'Evolve beyond species limits while preserving identity.', 'The soul designs a body the world has never named.', NULL, '{"transcendentEvolution":true}', '{"skills":["evolution"],"soulLevel":15}', '{"impossibleAchievement":"reject_forced_divinity"}', NULL),
('eternal-reincarnation', 6, 'Eternal Reincarnation', 'ultimate', 'Soul', 'mythic', 'hidden', 6, 'Carry a chosen fragment of body mastery into the next reincarnation.', 'Death closes the life, but one earned truth refuses to be buried.', NULL, '{"carryMasteryAcrossLife":true}', '{"skills":["endless-will","reincarnation-instinct"]}', '{"completedLives":3,"impossibleAchievement":"die_by_choice_to_save_world"}', NULL),
('soul-archive', 6, 'Soul Archive', 'passive', 'Soul', 'mythic', 'hidden', 5, 'Enter a perfect internal archive of meaningful memories from every life.', 'Every lost face waits behind a door bearing your first name.', NULL, '{"perfectLifeMemory":true}', '{"totalDeaths":5}', '{"impossibleAchievement":"restore_erased_companion_memory"}', '{"nextSkills":["azrael-lord-of-souls"]}'),
('origin-magic', 4, 'Origin Magic', 'ultimate', 'Arcane', 'mythic', 'hidden', 6, 'Shape magic before it separates into elements and schools.', 'Mana answers in a language older than fire, light, or death.', NULL, '{"preElementalMagic":true}', '{"familyMastery":"arcane"}', '{"impossibleAchievement":"cast_without_world_magic_laws"}', NULL),
('dimensional-rift', 3, 'Dimensional Rift', 'active', 'Space', 'mythic', 'hidden', 5, 'Open a temporary passage between two known points or spaces.', 'The world parts like cloth cut by an invisible blade.', NULL, '{"openRift":true}', '{"skills":["void-step","spatial-storage"]}', '{"impossibleAchievement":"escape_sealed_dimension"}', '{"nextSkills":["void-dominion"]}');

-- Ultimate skills are mythical family conclusions or world-level authorities.
INSERT INTO skills (skill_key, family_id, name, skill_type, category, rarity, visibility, family_tier, description, identity_text, unlock_hint, effects_json, requirements_json, discovery_rules_json, evolution_rules_json) VALUES
('azrael-lord-of-souls', 6, 'Azrael, Lord of Souls', 'ultimate', 'Soul', 'mythic', 'secret', 6, 'Command soul chains, archives, and the boundary between life and death.', 'The dead do not kneel. They recognize one who remembers them.', 'Master the Soul Family without surrendering your humanity.', '{"soulSovereignty":true}', '{"familyMastery":"soul","skills":["soul-devour","soul-chain","soul-archive"]}', '{"soulsSavedAndReleased":100}', NULL),
('leviathan-ocean-sovereign', NULL, 'Leviathan, Ocean Sovereign', 'ultimate', 'Ocean', 'mythic', 'secret', 6, 'Command crushing tides, abyssal pressure, and sea-born creatures.', 'The ocean rises because something beneath it opened an eye.', 'Earn recognition from the deepest living sea.', '{"oceanSovereignty":true}', '{"realmCleared":8}', '{"defeatOceanBossWithoutLeavingWater":true}', NULL),
('beelzar-king-of-consumption', 1, 'Beelzar, King of Consumption', 'ultimate', 'Predator', 'mythic', 'secret', 6, 'Consume hostile power, curses, and magic without losing identity.', 'Hunger wears a crown, but the soul beneath it still chooses.', 'Master consumption without becoming hunger itself.', '{"consumePower":true,"consumeCurse":true}', '{"familyMastery":"predator","skills":["soul-devour"]}', '{"refuseCorruptingFeast":true}', NULL),
('ragnarok-drive', 4, 'Ragnarok Drive', 'ultimate', 'Arcane', 'mythic', 'secret', 6, 'Overdrive every active core and skill for a brief catastrophic state.', 'Every limit breaks at once, and the body begins counting the cost.', 'Survive deliberate magical overdrive.', '{"temporaryOverdrive":true,"severeAftereffect":true}', '{"skills":["mana-core","mana-burst"]}', '{"surviveCoreCollapse":true}', NULL),
('genesis-authority', NULL, 'Genesis Authority', 'ultimate', 'Creation', 'mythic', 'secret', 6, 'Create lasting life or matter under strict soul-defined limits.', 'Something exists because you accepted responsibility for its future.', 'Create rather than conquer when destruction would be easier.', '{"lastingCreation":true}', '{"skills":["origin-magic"]}', '{"createLivingSanctuary":true}', NULL),
('celestial-throne', 5, 'Celestial Throne', 'ultimate', 'Monarch', 'mythic', 'secret', 6, 'Manifest a throne-domain powered by loyalty, law, and chosen responsibility.', 'A throne appears only after everyone else has somewhere safe to stand.', 'Become a ruler without taking freedom from those who follow.', '{"throneDomain":true}', '{"familyMastery":"monarch","skills":["absolute-presence"]}', '{"followersChooseCoronation":true}', NULL),
('eclipse-monarch', 3, 'Eclipse Monarch', 'ultimate', 'Shadow/Monarch', 'mythic', 'secret', 6, 'Rule a domain where light and shadow obey a single sovereign will.', 'Day and night overlap, waiting for your judgment.', 'Master both authority and shadow without becoming a tyrant.', '{"eclipseDomain":true}', '{"skills":["shadow-clone","absolute-presence","black-flame"]}', '{"saveEnemiesInsideOwnDomain":true}', NULL),
('infinite-arsenal', 4, 'Infinite Arsenal', 'ultimate', 'Creation/Space', 'mythic', 'secret', 6, 'Store and summon every mastered arcane weapon pattern.', 'A horizon of remembered weapons opens behind you.', 'Create, master, and preserve weapons instead of merely collecting them.', '{"summonMasteredWeapons":true}', '{"skills":["arcane-creation","spatial-storage"]}', '{"uniqueWeaponsMastered":50}', NULL),
('dragon-emperor', 2, 'Dragon Emperor', 'ultimate', 'Dragon', 'mythic', 'secret', 6, 'Manifest complete draconic sovereignty over breath, scale, and fear.', 'The sky lowers itself to hear your roar.', 'Earn the allegiance of dragons after defeating one without hatred.', '{"dragonSovereignty":true}', '{"familyMastery":"dragon","skills":["dragon-breath","dragon-scales","dragon-fear"]}', '{"dragonAllegiance":3}', NULL),
('void-genesis', 3, 'Void Genesis', 'ultimate', 'Void/Creation', 'mythic', 'secret', 6, 'Create stable form inside absolute nothingness.', 'In the place where nothing can exist, your first light chooses to remain.', 'Create a refuge within the Void.', '{"createInsideVoid":true}', '{"familyMastery":"shadow","skills":["void-dominion","genesis-authority"]}', '{"createVoidSanctuary":true}', NULL);
