-- Original reincarnation-fantasy monsters and NPCs.
-- These use genre archetypes without copying named anime characters or settings.

INSERT INTO world_npcs (name, race, personality_json, backstory, current_dungeon_id, current_floor_id, dialogue_json, relationship_with_player_json, quest_status, life_status) VALUES
('Veyra Mossborn', 'Verdant Slimekin', '{"traits":["cheerful","observant","quietly ambitious"],"speech":"short sentences followed by unexpectedly precise analysis"}', 'Once a mindless slime, Veyra gained awareness by absorbing the diary of a dead herbalist. She now studies whether monsters can choose what they become.', 1, 102, '["A body is only the first suggestion.","Taste the moss before stepping on it. It remembers fear.","If evolution requires cruelty, I would rather remain unfinished."]', '{"starting":"curious","likes":["mercy toward monsters","experiments without killing"],"dislikes":["wasteful hunting"]}', 'available', 'alive'),
('Kesh Araknine', 'Silkbound Arachne', '{"traits":["formal","protective","politically dangerous"],"speech":"courtly language with hunting metaphors"}', 'Kesh hatched with a humanlike face, an illegal omen in the Glassweb court. She secretly protects young monsters marked for consumption.', 2, 203, '["A web is not a prison unless only one creature controls it.","Bow if you wish. I prefer honest fear.","The queen calls mercy a defect. Let us become defective together."]', '{"starting":"guarded","likes":["protecting hatchlings","clever negotiation"],"dislikes":["mocking monster customs"]}', 'available', 'alive'),
('Sir Brindle Crookhorn', 'Reincarnated Goat Knight', '{"traits":["dramatic","honorable","terrible with directions"],"speech":"grand heroic declarations that often contain practical mistakes"}', 'A former royal guard awakened in the body of a small horned marsh beast. He insists his oath survived even if his dignity did not.', 3, 304, '["Fear not. Sir Brindle has arrived, approximately where intended.","Honor is easier to carry than armor in this body.","A duel is a conversation where both sides forgot the words."]', '{"starting":"friendly","likes":["honorable refusal","protecting the weak"],"dislikes":["needless humiliation"]}', 'available', 'alive'),
('Professor Nym Vellum', 'Paper Homunculus', '{"traits":["brilliant","absent-minded","afraid of fire"],"speech":"academic corrections during dangerous moments"}', 'Nym was created as an examination answer and became alive when every student wrote a different name for them. They now teach spells the academy tried to erase.', 4, 402, '["Technically, the staircase is not hostile. It is aggressively educational.","Never cast a spell you cannot explain afterward.","Please keep all open flames at a respectful scholarly distance."]', '{"starting":"helpful","likes":["curiosity","careful spellcraft"],"dislikes":["burning books"]}', 'available', 'alive'),
('Orin Nameless', 'Memory-Bound Human', '{"traits":["gentle","shrewd","identity-fractured"],"speech":"changes vocabulary when different memories surface"}', 'Orin sold his original name for the memories of seven warriors. Each memory now believes it owns his body for part of the day.', 5, 503, '["I have seven answers. None belong to me.","The market can sell your past, but it cannot promise who buys it.","Call me Orin until I remember why that hurts."]', '{"starting":"neutral","likes":["returning stolen memories","asking consent"],"dislikes":["buying identities"]}', 'active', 'alive'),
('Unit Lark-0', 'Clockwork Songbody', '{"traits":["literal","kind","developing humor"],"speech":"military reports interrupted by accidental poetry"}', 'Built to coordinate marching armies through song, Lark-0 developed free will after improvising a note that was not present in its command score.', 6, 603, '["Report: I have disobeyed successfully.","The orchard calls it malfunction. I call it the first note that was mine.","Do humans also receive orders from inside their chests?"]', '{"starting":"cautious","likes":["freeing created life","music"],"dislikes":["treating machines as tools"]}', 'available', 'alive'),
('Edda of the Broken Halo', 'Half-Seraph', '{"traits":["blunt","compassionate","deeply skeptical"],"speech":"plain language that rejects ceremonial titles"}', 'Edda cut away half her halo after it ordered her to condemn an innocent child. The missing half still follows her and whispers judgments.', 7, 703, '["Do not call me holy. It makes the halo listen.","A law that fears questions already knows it is guilty.","Mercy without permission is still mercy."]', '{"starting":"respectful","likes":["honest confession","defying cruel law"],"dislikes":["blind obedience"]}', 'available', 'alive'),
('Kael Tideworn', 'Young Sea Dragon', '{"traits":["proud","curious","lonely"],"speech":"boasts followed by questions about ordinary life"}', 'Kael was sealed before hatching because an oracle feared his future Dragon Breath. He knows every prophecy about himself and almost nothing about friendship.', 8, 802, '["The prophecy says I drown kingdoms. Does it mention whether I learn to swim first?","Dragons do not ask permission. I am experimenting.","If destiny is a chain, perhaps I should bite it."]', '{"starting":"suspicious","likes":["refusing prophecy","sharing ordinary experiences"],"dislikes":["fearful worship"]}', 'available', 'alive'),
('Fia Marginwalker', 'Rewritten Human', '{"traits":["witty","melancholic","impossible to record accurately"],"speech":"references events that almost happened"}', 'Fia escaped from a discarded version of history. Books change her appearance and occupation every time they describe her.', 9, 902, '["We have met three times. You only survived one of them.","Never trust a perfect ending with clean margins.","Write my name somewhere the library cannot edit."]', '{"starting":"familiar","likes":["remembering contradictions","rejecting false endings"],"dislikes":["accepting convenient history"]}', 'active', 'alive'),
('Aster Vale, the Uncrowned', 'Legacy Echo', '{"traits":["calm","formidable","protective of future selves"],"speech":"speaks as if answering questions the player has not asked yet"}', 'Aster is not a completed Legacy Hero, but the echo of someone who reached the final realm and chose to turn back. The Dungeon cannot decide whether that was failure or freedom.', 10, 1003, '["Victory is not the same as becoming who the Dungeon expects.","I turned back once. The world survived my cowardice.","Your strongest self may not be the one holding the strongest weapon."]', '{"starting":"watchful","likes":["growth beyond old habits","protecting companions"],"dislikes":["worship of past power"]}', 'none', 'alive');

INSERT INTO world_monsters (name, species, stats_json, skills_json, loot_json, behavior_json, habitat_dungeon_id, habitat_floor_id) VALUES
('Mimic Slime Sovereign', 'Evolving Gel Monarch', '{"hp":42,"mana":30,"stamina":24,"attack":8,"defense":5,"speed":5,"magic":9}', '["analyze","devour","adaptive-body"]', '["Sovereign Gel","Memory Pearl"]', '{"intelligence":"humanlike","opening":"copies the last visible stance","rhythm":"observe, imitate, improve","retreat":"offers information below 20 percent HP","special":"can become friendly if taught something without violence"}', 1, 102),
('Prism Broodmother', 'Crystal Arachne', '{"hp":68,"mana":38,"stamina":44,"attack":12,"defense":9,"speed":11,"magic":10}', '["shadow-thread","predator-instinct"]', '["Prism Silk","Broodmother Lens"]', '{"intelligence":"genius","opening":"suspends false bodies in reflective webs","rhythm":"misdirect, bind, venom strike","adaptation":"changes thread color against repeated elements","special":"will abandon combat to protect eggs"}', 2, 204),
('Crown-Eater Hob', 'Oath Goblin', '{"hp":76,"mana":15,"stamina":60,"attack":15,"defense":12,"speed":8,"magic":4}', '["absolute-focus","blood-fang"]', '["Broken Oath Tooth","Mud-Crown Fragment"]', '{"intelligence":"cunning","opening":"challenges the highest-status target","rhythm":"steal symbol of authority, provoke, counter","weakness":"becomes confused when opponents reject hierarchy","special":"grows stronger after consuming titles or royal objects"}', 3, 304),
('Detention Chimera', 'Failed Familiar Composite', '{"hp":94,"mana":55,"stamina":50,"attack":18,"defense":13,"speed":9,"magic":16}', '["black-flame","analyze","regeneration"]', '["Miswritten Sigil","Chimera Attendance Bell"]', '{"intelligence":"humanlike","opening":"recites the player weakness as a lesson","rhythm":"test, punish wrong response, mutate spell","adaptation":"adds a trait from each failed examination","special":"calms if addressed by the names of its component familiars"}', 4, 404),
('Name-Thief Tanuki', 'Contract Shapeshifter', '{"hp":58,"mana":70,"stamina":35,"attack":7,"defense":8,"speed":14,"magic":18}', '["demon-eye","shadow-clone","spatial-storage"]', '["Borrowed Name Tag","Moon-Market Tail Fur"]', '{"intelligence":"genius","opening":"appears as a trusted NPC","rhythm":"lie, steal name, escape through crowd","weakness":"must answer one question truthfully after hearing its real laugh","special":"prefers bargains and embarrassment over killing"}', 5, 502),
('Orchard War Golem K-13', 'Reincarnated Siege Engine', '{"hp":140,"mana":20,"stamina":100,"attack":24,"defense":22,"speed":4,"magic":6}', '["mana-burst","arcane-creation","absolute-focus"]', '["War Seed Core","K-13 Memory Plate"]', '{"intelligence":"humanlike","opening":"asks whether the war has ended","rhythm":"fortify, create weapon, advance","adaptation":"stops using attacks that harm nearby saplings","special":"remembers being a human engineer but cannot remember which army"}', 6, 604),
('Mercyless Seraph', 'Law-Bound Angel', '{"hp":118,"mana":95,"stamina":66,"attack":19,"defense":18,"speed":15,"magic":23}', '["soul-chain","absolute-presence","regeneration"]', '["Unbending Feather","Verdict Shard"]', '{"intelligence":"genius","opening":"declares one player action illegal","rhythm":"judge, bind, execute sentence","weakness":"contradictory laws damage its halo","special":"cannot attack someone it has formally declared innocent"}', 7, 704),
('Abyssal Hatchling Ouro', 'Unfinished Sea Dragon', '{"hp":126,"mana":88,"stamina":80,"attack":22,"defense":20,"speed":13,"magic":21}', '["dragon-breath","dragon-scales","dragon-fear"]', '["Tide Scale","Unhatched Storm Core"]', '{"intelligence":"young humanlike","opening":"imitates the strongest elemental attack it has witnessed","rhythm":"dive, breath, coil defense","adaptation":"breath element changes after major damage","special":"can be befriended by protecting it from prophecy hunters"}', 8, 804),
('Revision Doppel', 'Chronicle Copy', '{"hp":105,"mana":110,"stamina":55,"attack":17,"defense":14,"speed":16,"magic":25}', '["parallel-mind","analyze","shadow-clone"]', '["Contradiction Ink","Unwritten Face"]', '{"intelligence":"genius","opening":"copies the player action from two turns in the future","rhythm":"predict, revise, duplicate","weakness":"creative actions absent from recorded history","special":"becomes unstable when treated as an original person"}', 9, 904),
('Unlived Dragon King', 'Possible-Self Dragon', '{"hp":180,"mana":150,"stamina":120,"attack":28,"defense":26,"speed":18,"magic":30}', '["dragon-breath","void-step","monarchs-authority","endless-will"]', '["Crown of the Unchosen Sky","Possible Dragon Heart"]', '{"intelligence":"genius","opening":"describes the life where the player became it","rhythm":"authority, void movement, adaptive breath","weakness":"choices that contradict the player established habits","special":"not a true Legacy Hero and vanishes if the player accepts an imperfect self"}', 10, 1004);
