-- Content expansion: 20 NPCs, 20 monsters, 12 items, 5 skills, quests, and events.

INSERT INTO items (item_key, name, item_type, description, rarity, effects_json, lore_json) VALUES
('ashhide-pelt', 'Ashhide Pelt', 'material', 'Heat-resistant hide taken from a Cradlewood predator.', 'common', '{"crafting":["fire_resistant_armor"]}', '{"realm":1}'),
('memory-pearl', 'Memory Pearl', 'relic', 'A silver sphere holding the final instinct of an evolving monster.', 'rare', '{"soulMemory":1,"consumable":true}', '{"realm":1,"legacyCompatible":true}'),
('prism-silk', 'Prism Silk', 'material', 'Glassweb silk that changes resistance with reflected light.', 'rare', '{"crafting":["adaptive_cloak"]}', '{"realm":2}'),
('oath-tooth', 'Broken Oath Tooth', 'accessory', 'A goblin oath carved into a fang and broken without dishonor.', 'uncommon', '{"resolve":2,"charisma":1}', '{"realm":3}'),
('living-chalk', 'Living Chalk', 'quest', 'Chalk that writes corrections before a spell is completed.', 'rare', '{"analyzeMagic":2,"consumable":false}', '{"realm":4}'),
('borrowed-name-tag', 'Borrowed Name Tag', 'accessory', 'A market token bearing a name that changes when nobody watches.', 'cursed', '{"charisma":3,"identityRisk":1}', '{"realm":5}'),
('war-seed-core', 'War Seed Core', 'relic', 'The dormant command heart of an orchard war machine.', 'epic', '{"defense":4,"mana":15}', '{"realm":6,"legacyCompatible":true}'),
('unbending-feather', 'Unbending Feather', 'accessory', 'A seraph feather that refuses commands it judges contradictory.', 'epic', '{"resolve":4,"confusionResistance":0.35}', '{"realm":7}'),
('tide-scale', 'Tide Scale', 'armor', 'A young sea dragon scale that hardens when submerged.', 'epic', '{"defense":5,"waterResistance":0.4}', '{"realm":8}'),
('contradiction-ink', 'Contradiction Ink', 'consumable', 'Ink that forces one false written fact to reveal itself.', 'rare', '{"uses":1,"revealsFalseHistory":true}', '{"realm":9}'),
('possible-dragon-heart', 'Possible Dragon Heart', 'relic', 'A heart from a future that never became real.', 'legendary', '{"maxHp":30,"thaumaturgy":5,"soulEnergy":25}', '{"realm":10,"legacyCompatible":true}'),
('soulglass-tonic', 'Soulglass Tonic', 'consumable', 'A restorative draught that heals flesh but briefly exposes soul memories.', 'uncommon', '{"uses":1,"heal":40,"manaRestore":20,"statusRemove":["poisoned","bleeding"]}', '{"craftedBy":"soul_apothecaries"}');

INSERT INTO skills (skill_key, family_id, name, skill_type, category, rarity, visibility, family_tier, description, identity_text, unlock_hint, effects_json, requirements_json, discovery_rules_json, evolution_rules_json) VALUES
('grave-bloom', 6, 'Grave Bloom', 'active', 'Soul/Nature', 'epic', 'secret', 3, 'Grow spectral flowers from a place where someone died and read the emotion left behind.', 'Pale petals open around a memory the earth refused to forget.', 'Show respect at three places of death.', '{"memoryReveal":true,"spiritHealing":15}', '{"resolve":9}', '{"respectfulDeathSites":3,"uniqueContexts":3}', '{"nextSkills":["soul-archive"]}'),
('starving-mirror', 1, 'Starving Mirror', 'reaction', 'Predator', 'legendary', 'hidden', 4, 'Reflect one devouring ability back at its source and steal its hunger.', 'The enemy sees its appetite looking back from your eyes.', NULL, '{"reflectConsume":true,"adaptationProgress":3}', '{"skills":["predator","analyze"]}', '{"achievement":"survive_devour_and_reflect","uniqueBoss":true}', '{"nextSkills":["absolute-predator"]}'),
('dragonheart-covenant', 2, 'Dragonheart Covenant', 'passive', 'Dragon/Social', 'legendary', 'secret', 4, 'Share resistance and resolve with a dragon companion through mutual consent.', 'Two heartbeats agree to defend the same future.', 'Earn a dragon companion without domination.', '{"sharedResistance":true,"companionBondBonus":true}', '{"loyalDragonCompanion":true}', '{"dragonTrust":80,"betrayal":0}', '{"nextSkills":["dragon-emperor"]}'),
('sovereign-silence', 5, 'Sovereign Silence', 'active', 'Monarch', 'mythic', 'hidden', 5, 'End all commands and authority effects in an area, including your own.', 'Every throne becomes only a chair until you choose to speak again.', NULL, '{"cancelAuthority":true,"durationTurns":3}', '{"skills":["royal-decree","absolute-presence"]}', '{"achievement":"surrender_authority_to_save_enemy"}', '{"nextSkills":["celestial-throne"]}'),
('memory-forge', 4, 'Memory Forge', 'active', 'Arcane/Soul', 'epic', 'secret', 3, 'Shape a remembered tool for one scene without recreating its original material.', 'Your hands rebuild an object from the certainty that it once existed.', 'Lose an important item, then solve a crisis by remembering its purpose.', '{"temporaryRememberedItem":true,"manaCost":18}', '{"skills":["arcane-creation","soul-echo"]}', '{"lostItemsRemembered":3,"uniqueContexts":3}', '{"nextSkills":["infinite-arsenal","soul-archive"]}');

INSERT INTO world_npcs (name, race, personality_json, backstory, current_dungeon_id, current_floor_id, dialogue_json, relationship_with_player_json, quest_status, life_status) VALUES
('Mara Fenroot', 'Human Herbalist', '{"traits":["practical","warm","secretive"],"companionRole":"healer"}', 'Mara survived Cradlewood by learning which plants remember kindness.', 1, 103, '["Hold still. The forest already took enough blood.","Medicine is a promise made to tomorrow."]', '{"trust":10,"likes":["healing","mercy"],"betrayalTriggers":["poisoning_allies"]}', 'available', 'alive'),
('Nox Brambletail', 'Thorn Foxkin', '{"traits":["mischievous","loyal","territorial"],"companionRole":"scout"}', 'Nox guides lost souls for a price he changes whenever they become friends.', 1, 104, '["I said I knew the path. I never said it stayed still.","Do not die before paying me."]', '{"trust":5,"likes":["cleverness","shared_food"]}', 'available', 'alive'),
('Ilyss Threadseer', 'Glassweb Oracle', '{"traits":["patient","eerie","honest"],"companionRole":"analyst"}', 'Ilyss reads futures in broken silk and cuts every thread that ends in ownership.', 2, 202, '["There are nine ways you leave this room. Only two remain yourself.","Fate is a web with poor maintenance."]', '{"trust":0,"fear":10,"likes":["rejecting_false_evolution"]}', 'available', 'alive'),
('Bramble Eightlegs', 'Armored Spiderkin', '{"traits":["boisterous","protective","hungry"],"companionRole":"tank"}', 'Bramble deserted the queen guard after being ordered to eat surrendered enemies.', 2, 204, '["Stand behind me. Most things cannot bite through all eight shoulders.","Surrender should mean the biting stops."]', '{"loyalty":15,"likes":["spare","protect"]}', 'available', 'alive'),
('Lady Silt Vane', 'Marsh Goblin Noble', '{"traits":["elegant","calculating","lonely"],"companionRole":"diplomat"}', 'Silt trades court secrets for proof that honor can survive politics.', 3, 303, '["Every smile here carries a small knife.","Tell me the truth quietly. Lies have excellent hearing."]', '{"trust":0,"fear":5,"likes":["honorable_negotiation"]}', 'active', 'alive'),
('Drokk Bellbelly', 'Bog Ogre Bard', '{"traits":["gentle","loud","perceptive"],"companionRole":"support"}', 'Drokk learned court law by turning every verdict into a drinking song.', 3, 301, '["A bad king fears a catchy chorus.","I can sing quietly. I simply choose justice."]', '{"trust":10,"likes":["music","defying_cruelty"]}', 'available', 'alive'),
('Tess Embernote', 'Human Ghost Student', '{"traits":["curious","reckless","brilliant"],"companionRole":"mage"}', 'Tess died during a forbidden practical exam and continues attending out of spite.', 4, 401, '["Death is not an excused absence apparently.","The spell worked. The room was the part that failed."]', '{"trust":5,"fear":0,"likes":["experimentation"]}', 'available', 'alive'),
('Custodian Rell', 'Broom Golem', '{"traits":["meticulous","deadpan","courageous"],"companionRole":"defender"}', 'Rell cleaned magical disasters until deciding prevention was more efficient.', 4, 404, '["Please bleed away from the clean tiles.","Threat classified as a severe stain."]', '{"loyalty":10,"likes":["protect_school"]}', 'available', 'alive'),
('Yara Twice-Sold', 'Demon Merchant', '{"traits":["charming","remorseful","resourceful"],"companionRole":"merchant"}', 'Yara sold her shadow twice and now both owners are searching for it.', 5, 501, '["Everything has a price. Regret charges interest.","I can get us inside. Getting our names back costs extra."]', '{"trust":0,"betrayal":5,"likes":["fair_bargains"]}', 'available', 'alive'),
('Little Coin', 'Living Mimic', '{"traits":["greedy","affectionate","easily distracted"],"companionRole":"storage"}', 'A coin purse mimic that decided friendship produces more snacks than ambushes.', 5, 504, '["Mine? Yours? Ours is acceptable.","No cursed coins before dinner."]', '{"loyalty":5,"likes":["feeding_items"]}', 'none', 'alive'),
('Vox Orchardson', 'Plantborn Mechanic', '{"traits":["inventive","stubborn","pacifist"],"companionRole":"engineer"}', 'Vox grows replacement parts and refuses to build anything that cannot choose its purpose.', 6, 602, '["A weapon is only a tool someone stopped questioning.","Give me oil, sunlight, and ten unreasonable minutes."]', '{"trust":10,"likes":["free_machine"]}', 'available', 'alive'),
('Captain Brassleaf', 'Iron Dryad', '{"traits":["disciplined","protective","guilt-ridden"],"companionRole":"fighter"}', 'Brassleaf commanded an orchard battalion before realizing the enemy villages were alive.', 6, 604, '["Orders explain an action. They do not forgive it.","I know every formation the General will grow."]', '{"loyalty":0,"betrayal":0,"likes":["protect_civilians"]}', 'active', 'alive'),
('Brother No-One', 'Maskless Penitent', '{"traits":["calm","empathetic","unsettling"],"companionRole":"healer"}', 'He surrendered his name so the Cathedral could not attach inherited guilt to it.', 7, 702, '["A nameless confession can still be true.","Guilt describes pain. It does not always describe sin."]', '{"trust":15,"likes":["honest_confession"]}', 'available', 'alive'),
('Choir-Spark Lume', 'Runaway Hymn', '{"traits":["joyful","naive","defiant"],"companionRole":"support"}', 'Lume is a living note that escaped a song commanding angels to kill.', 7, 704, '["I was written to end a life. I changed the melody.","Hum with me. The bells hate improvisation."]', '{"loyalty":10,"fear":5,"likes":["music","mercy"]}', 'available', 'alive'),
('Mako Chainfin', 'Shark Demon', '{"traits":["direct","funny","protective"],"companionRole":"fighter"}', 'Mako files prison chains into cooking knives and feeds anyone planning escape.', 8, 801, '["Revolution works better after breakfast.","I bite chains. People taste terrible."]', '{"trust":10,"likes":["free_prisoner"]}', 'available', 'alive'),
('Suri Stormshell', 'Turtle Dragonkin', '{"traits":["patient","wise","stubborn"],"companionRole":"tank"}', 'Suri carries a village map carved into her shell after the real village sank.', 8, 803, '["Slow is not the same as late.","A home can survive as directions we refuse to forget."]', '{"loyalty":15,"likes":["protect_refugees"]}', 'available', 'alive'),
('Comma', 'Ink Sprite', '{"traits":["pedantic","brave","anxious"],"companionRole":"analyst"}', 'Comma edits tiny pauses into fatal prophecies so heroes have time to escape.', 9, 902, '["Punctuation saves lives when applied aggressively.","Do not finish that sentence yet."]', '{"trust":5,"likes":["creative_wordplay"]}', 'available', 'alive'),
('Redacted Rose', 'Erased Knight', '{"traits":["solemn","loyal","identity-fractured"],"companionRole":"fighter"}', 'Every record of Rose was deleted, but her armor continues protecting forgotten people.', 9, 903, '["You do not need my name to accept my shield.","Remember what I chose, not what the book called me."]', '{"loyalty":20,"likes":["restore_memory"]}', 'available', 'alive'),
('Cairn Aftervictory', 'Abandoned Hero Echo', '{"traits":["tired","kind","dangerously capable"],"companionRole":"mentor"}', 'Cairn is the echo of a hero who won everything and discovered nobody remained to celebrate.', 10, 1002, '["Power answers how. It never answers why.","Leave someone alive to remember your victory."]', '{"trust":0,"fear":0,"likes":["protect_companions"]}', 'available', 'alive'),
('Moth-of-Last-Lantern', 'Soul Moth', '{"traits":["silent","gentle","ancient"],"companionRole":"soul_guide"}', 'The moth carries one final memory from every body the Dungeon abandoned.', 10, 1001, '["The moth speaks by showing you rain from another life.","Its wings open, and a forgotten face returns."]', '{"loyalty":10,"likes":["honor_dead"]}', 'none', 'alive');

INSERT INTO world_monsters (name, species, stats_json, skills_json, loot_json, behavior_json, habitat_dungeon_id, habitat_floor_id) VALUES
('Grief Antler', 'Memory Stag', '{"hp":36,"attack":6,"defense":4,"speed":10,"resistances":{"soul":0.3},"weaknesses":{"fire":0.2}}', '["predator-instinct"]', '["Ashhide Pelt"]', '{"targets":"most_fearful","statusOnHit":"confused","peace":"return a lost memory"}', 1, 102),
('Thornmouth Cub', 'Root Mimic', '{"hp":48,"attack":9,"defense":7,"speed":4,"resistances":{"physical":0.2},"weaknesses":{"fire":0.35}}', '["blood-fang"]', '["Heartroot Splinter"]', '{"targets":"nearest","statusOnHit":"bleeding","peace":"feed mineral-rich soil"}', 1, 104),
('Silkglass Duelist', 'Spider Knight', '{"hp":62,"attack":12,"defense":9,"speed":12,"resistances":{"dark":0.2},"weaknesses":{"impact":0.25}}', '["shadow-thread","void-step"]', '["Prism Silk"]', '{"targets":"highest_agility","opens":"binding duel","peace":"accept formal surrender"}', 2, 204),
('Egg-Mirror Wraith', 'Unborn Reflection', '{"hp":44,"attack":7,"defense":5,"magic":14,"resistances":{"magic":0.25},"weaknesses":{"soul":0.3}}', '["analyze","shadow-clone"]', '["Memory Pearl"]', '{"targets":"player","copies":"last_skill","statusOnHit":"confused"}', 2, 202),
('Reed-Oath Eel', 'Promise Parasite', '{"hp":58,"attack":11,"defense":6,"speed":13,"resistances":{"water":0.4},"weaknesses":{"lightning":0.4}}', '["soul-chain"]', '["Broken Oath Tooth"]', '{"targets":"character_with_broken_promise","statusOnHit":"silenced","peace":"fulfill spoken oath"}', 3, 302),
('Mudcourt Doppel', 'Goblin Reflection', '{"hp":70,"attack":13,"defense":10,"speed":8,"resistances":{"physical":0.15},"weaknesses":{"truth":0.5}}', '["demon-eye","absolute-focus"]', '["Broken Oath Tooth"]', '{"targets":"highest_charisma","copies":"social_action","peace":"publicly admit a fault"}', 3, 303),
('Red-Ink Prefect', 'Correction Spirit', '{"hp":74,"attack":10,"defense":10,"magic":17,"resistances":{"fire":0.3},"weaknesses":{"water":0.3}}', '["black-flame","analyze"]', '["Living Chalk"]', '{"targets":"last_spellcaster","statusOnHit":"burning","phase":"rewrites failed spells"}', 4, 404),
('Homework Hydra', 'Scholastic Chimera', '{"hp":88,"attack":15,"defense":12,"magic":12,"resistances":{"cutting":0.2},"weaknesses":{"correct_answer":0.5}}', '["regeneration","parallel-mind"]', '["Living Chalk"]', '{"targets":"lowest_intelligence","heads":"grow after repeated attack","peace":"solve three questions"}', 4, 402),
('Receipt Lich', 'Debt Undead', '{"hp":82,"attack":12,"defense":8,"magic":20,"resistances":{"dark":0.4},"weaknesses":{"contract_loophole":0.6}}', '["soul-chain","spatial-storage"]', '["Borrowed Name Tag"]', '{"targets":"highest_gold","steals":"gold_on_hit","statusOnHit":"cursed"}', 5, 505),
('Memory Moth Swarm', 'Thought Eater', '{"hp":52,"attack":8,"defense":4,"speed":16,"magic":15,"resistances":{"physical":0.5},"weaknesses":{"light":0.4}}', '["soul-devour"]', '["Memory Pearl"]', '{"targets":"most_memories","statusOnHit":"confused","peace":"offer an unimportant memory"}', 5, 503),
('Harvest Knight Beta', 'Grown Automaton', '{"hp":110,"attack":18,"defense":18,"speed":6,"resistances":{"physical":0.3},"weaknesses":{"lightning":0.35}}', '["arcane-creation","mana-burst"]', '["War Seed Core"]', '{"targets":"armed_target","phase":"changes weapon each round","peace":"issue valid stand-down code"}', 6, 604),
('Rustflower Locust', 'Machine Swarm', '{"hp":65,"attack":13,"defense":8,"speed":17,"resistances":{"poison":1},"weaknesses":{"water":0.3}}', '["predator-instinct"]', '["War Seed Core"]', '{"targets":"equipment","damages":"equipped_item","statusOnHit":"bleeding"}', 6, 601),
('Confession Leech', 'Guilt Parasite', '{"hp":60,"attack":9,"defense":5,"magic":18,"resistances":{"soul":0.4},"weaknesses":{"honest_confession":0.7}}', '["demon-eye","soul-devour"]', '["Unbending Feather"]', '{"targets":"hidden_secret","statusOnHit":"confused","peace":"truth without self-condemnation"}', 7, 702),
('Halo Bailiff', 'Judgment Construct', '{"hp":105,"attack":17,"defense":16,"magic":16,"resistances":{"light":0.5},"weaknesses":{"contradiction":0.5}}', '["absolute-presence","soul-chain"]', '["Unbending Feather"]', '{"targets":"declared_guilty","phase":"adds law each round","peace":"invalidate its jurisdiction"}', 7, 703),
('Stormjaw Ray', 'Chain Sea Beast', '{"hp":96,"attack":17,"defense":11,"speed":15,"resistances":{"water":0.6,"lightning":0.2},"weaknesses":{"earth":0.35}}', '["dragon-breath","void-step"]', '["Tide Scale"]', '{"targets":"isolated_target","statusOnHit":"shocked","peace":"remove embedded chain"}', 8, 804),
('Prophecy Hunter', 'Future-Bound Demon', '{"hp":90,"attack":16,"defense":13,"magic":16,"resistances":{"fire":0.2},"weaknesses":{"unpredictable":0.5}}', '["analyze","dragon-fear"]', '["Tide Scale"]', '{"targets":"dragon_allies","predicts":"repeated_actions","peace":"prove prophecy already false"}', 8, 803),
('Footnote Basilisk', 'Grammar Beast', '{"hp":92,"attack":15,"defense":14,"magic":19,"resistances":{"magic":0.3},"weaknesses":{"wordplay":0.45}}', '["demon-eye","absolute-focus"]', '["Contradiction Ink"]', '{"targets":"reader","statusOnHit":"frozen","gaze":"turns claims into facts"}', 9, 902),
('Ending Shepherd', 'False Paradise Keeper', '{"hp":108,"attack":14,"defense":15,"magic":24,"resistances":{"soul":0.3},"weaknesses":{"rejected_comfort":0.5}}', '["parallel-mind","soul-chain"]', '["Contradiction Ink"]', '{"targets":"most_tired","statusOnHit":"sleeping","peace":"choose painful reality"}', 9, 904),
('Habit Colossus', 'Strategy Echo', '{"hp":145,"attack":22,"defense":20,"speed":9,"resistances":{"repeated":0.7},"weaknesses":{"creative_action":0.5}}', '["absolute-focus","regeneration","analyze"]', '["Possible Dragon Heart"]', '{"targets":"player","copies":"most_used_skill","phase":"gains resistance to repeated action"}', 10, 1004),
('Crownless Soulstorm', 'Failed Legacy Swarm', '{"hp":132,"attack":20,"defense":16,"magic":28,"resistances":{"soul":0.5},"weaknesses":{"accepted_failure":0.5}}', '["soul-devour","shadow-clone","endless-will"]', '["Possible Dragon Heart"]', '{"targets":"highest_soul_energy","statusOnHit":"confused","phase":"changes into abandoned body"}', 10, 1002);

CREATE TABLE world_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_key VARCHAR(120) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  dungeon_id BIGINT UNSIGNED NOT NULL,
  floor_id BIGINT UNSIGNED NOT NULL,
  description TEXT NOT NULL,
  trigger_rules_json JSON NOT NULL,
  outcomes_json JSON NOT NULL,
  repeatable TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_world_events_dungeon FOREIGN KEY (dungeon_id) REFERENCES dungeons(id) ON DELETE CASCADE,
  CONSTRAINT fk_world_events_floor FOREIGN KEY (floor_id) REFERENCES dungeon_floors(id) ON DELETE CASCADE
);

CREATE TABLE cycle_events (
  story_cycle_id BIGINT UNSIGNED NOT NULL,
  world_event_id BIGINT UNSIGNED NOT NULL,
  status ENUM('hidden', 'available', 'triggered', 'completed', 'failed') NOT NULL DEFAULT 'hidden',
  state_json JSON NOT NULL,
  triggered_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  PRIMARY KEY (story_cycle_id, world_event_id),
  CONSTRAINT fk_cycle_events_cycle FOREIGN KEY (story_cycle_id) REFERENCES story_cycles(id) ON DELETE CASCADE,
  CONSTRAINT fk_cycle_events_world FOREIGN KEY (world_event_id) REFERENCES world_events(id) ON DELETE CASCADE
);

INSERT INTO world_events (event_key, name, dungeon_id, floor_id, description, trigger_rules_json, outcomes_json) VALUES
('moss-remembers-mercy', 'The Moss Remembers Mercy', 1, 102, 'The path reveals a memory only after the player spares a frightened creature.', '{"signatures":["spare","protect"],"required":1}', '{"memory":"forest_mercy","skillProgress":{"grave-bloom":1}}'),
('queenless-web', 'A Web Without a Queen', 2, 203, 'Protected hatchlings ask the player to help design a kinder law.', '{"quest":"glassweb-hatchlings","status":"completed"}', '{"npcTrust":15,"worldFlag":"hatchling_council"}'),
('mud-crown-election', 'The Crown That Asked Permission', 3, 303, 'The court attempts its first vote after the player rejects inherited rule.', '{"signatures":["negotiate","refuse"],"required":2}', '{"worldFlag":"mire_election","gold":40}'),
('ghost-graduation', 'Graduation for the Dead', 4, 403, 'The final dead students can leave if someone completes their unfinished lesson.', '{"signatures":["solve","analyze"],"required":2}', '{"worldFlag":"students_released","soulEnergy":20}'),
('shadow-auction', 'The Auction of One Shadow', 5, 503, 'Two owners bid for Yara while her shadow asks to own itself.', '{"npc":"Yara Twice-Sold","signatures":["refuse_bargain","protect"]}', '{"companionCandidate":"Yara Twice-Sold","item":"Borrowed Name Tag"}'),
('machine-lullaby', 'A Song No General Ordered', 6, 603, 'Awakened machines stop marching to hear Lark and Lume improvise.', '{"signatures":["create","free"],"required":2}', '{"worldFlag":"orchard_ceasefire","npcTrust":10}'),
('halo-refuses', 'The Halo Refuses Judgment', 7, 703, 'A broken halo chooses mercy against its own law.', '{"signatures":["challenge_law","show_mercy"]}', '{"worldFlag":"halo_awakened","item":"Unbending Feather"}'),
('dragon-first-choice', 'A Dragon Chooses First', 8, 803, 'Kael chooses an act absent from every prophecy.', '{"signatures":["reject_prophecy","protect_dragon"]}', '{"companionCandidate":"Kael Tideworn","skillProgress":{"dragonheart-covenant":2}}'),
('name-in-margin', 'A Name Outside the Margin', 9, 903, 'Fia and Rose are written into a memory the library cannot revise.', '{"signatures":["restore_name","remember"]}', '{"worldFlag":"uneditable_names","skillProgress":{"memory-forge":2}}'),
('throne-left-empty', 'The Throne Left Empty', 10, 1003, 'The player refuses authority long enough to save an enemy.', '{"signatures":["refuse","protect"],"required":2}', '{"achievement":"surrender_authority_to_save_enemy","skillProgress":{"sovereign-silence":5}}');

INSERT INTO quests (quest_key, name, description, giver_npc_id, dungeon_id, floor_id, objectives_json, rewards_json, consequence_rules_json)
SELECT 'fenroot-remedy', 'Medicine for a Living Forest', 'Gather mercy-grown herbs and treat a wounded creature.', id, 1, 103, '{"actionSignatures":["heal","protect"],"required":3}', '{"xp":80,"gold":25,"item":"Soulglass Tonic"}', '{"failureActions":["burn_herbs"]}' FROM world_npcs WHERE name = 'Mara Fenroot' LIMIT 1;

INSERT INTO quests (quest_key, name, description, giver_npc_id, dungeon_id, floor_id, objectives_json, rewards_json, consequence_rules_json)
SELECT 'threadseer-futures', 'Cut the Cruel Future', 'Find and sever futures built on hatchling sacrifice.', id, 2, 202, '{"actionSignatures":["analyze","protect","refuse"],"required":3}', '{"xp":110,"gold":35,"item":"Prism Silk"}', '{"failureActions":["accept_sacrifice"]}' FROM world_npcs WHERE name = 'Ilyss Threadseer' LIMIT 1;

INSERT INTO quests (quest_key, name, description, giver_npc_id, dungeon_id, floor_id, objectives_json, rewards_json, consequence_rules_json)
SELECT 'free-note', 'The Note That Chose Itself', 'Help the awakened machines create a command-free song.', id, 6, 603, '{"actionSignatures":["create","free","protect"],"required":3}', '{"xp":240,"gold":90,"item":"War Seed Core"}', '{"failureActions":["enslave_machine"]}' FROM world_npcs WHERE name = 'Unit Lark-0' LIMIT 1;

INSERT INTO quests (quest_key, name, description, giver_npc_id, dungeon_id, floor_id, objectives_json, rewards_json, consequence_rules_json)
SELECT 'stormshell-home', 'A Village Carried on a Shell', 'Protect refugees while Suri finds ground for a new home.', id, 8, 803, '{"actionSignatures":["protect","explore","befriend"],"required":3}', '{"xp":340,"gold":140,"item":"Tide Scale"}', '{"failureActions":["abandon_refugees"]}' FROM world_npcs WHERE name = 'Suri Stormshell' LIMIT 1;

INSERT INTO quests (quest_key, name, description, giver_npc_id, dungeon_id, floor_id, objectives_json, rewards_json, consequence_rules_json)
SELECT 'remember-redacted', 'The Knight the Book Refused', 'Restore the deeds of Redacted Rose without inventing a false identity.', id, 9, 903, '{"actionSignatures":["remember","restore_name","analyze"],"required":3}', '{"xp":420,"gold":180,"item":"Contradiction Ink"}', '{"failureActions":["accept_false_history"]}' FROM world_npcs WHERE name = 'Redacted Rose' LIMIT 1;
