SET @ant_world_book_id = (SELECT book_id FROM deep_saga_books WHERE slug = 'ant-world' LIMIT 1);

INSERT INTO deep_saga_chapters
  (book_id, chapter_number, slug, title, purpose, required_canon_json, major_revelations_json, possible_developments_json, end_conditions_json, blocked_revelations_json, scene_guidance_json)
VALUES
(@ant_world_book_id, 1, 'the-strange-larva', 'The Strange Larva', 'The protagonist awakens in the nursery, discovers ant existence, human memory, pheromone meaning, an unusually attentive worker, and the first sign of a strange colony disturbance.', JSON_ARRAY('player awakens as an ant larva', 'human death memory retained', 'pheromones carry meaning', 'one worker notices the strange larva', 'something old and strange moves through the colony'), JSON_ARRAY('pheromone carries meaning', 'the protagonist is unusual to at least one worker', 'a bitter non-normal scent or disturbance enters colony awareness'), JSON_ARRAY('investigation through scent study', 'relationship through fear, hiding, worker attention, or protection', 'conflict through biting, resistance, and colony alert', 'accidental discovery through being moved, carried, or displaced'), JSON_ARRAY('the old disturbance has entered or affected the colony and the protagonist has experienced it through their chosen route'), JSON_ARRAY('Soul Seed identity', 'ancient chamber full truth', 'full Ant King revelation', 'Royal Soul Resonance name', 'tournament truth', 'sanctuary truth', 'final enemy'), JSON_ARRAY('awakening', 'nursery', 'pheromone-language', 'worker-attention', 'strange-scent', 'colony-disturbance')),
(@ant_world_book_id, 2, 'beneath-the-colony', 'Beneath the Colony', 'The colony investigates tunnel disturbances, and the player route leads naturally toward knowledge of an old sealed passage and ancient chamber beneath the colony.', JSON_ARRAY('colony investigates tunnel disturbance', 'old sealed passage becomes relevant', 'ancient underground chamber beneath the colony is established'), JSON_ARRAY('the disturbance is connected to old sealed spaces', 'there is something ancient beneath the colony'), JSON_ARRAY('analytical evidence and deduction', 'worker relationship and evacuation pressure', 'guard movement, danger, injury, or retreat', 'accidental separation or being carried into new spaces'), JSON_ARRAY('the protagonist knows an ancient chamber exists, though route-specific knowledge differs'), JSON_ARRAY('Soul Seed awakening', 'crowned ancient ant vision', 'complete King legacy truth', 'tournament soul energy', 'sanctuary truth', 'final enemy'), JSON_ARRAY('tunnel-disturbance', 'colony-investigation', 'sealed-passage', 'route-specific-discovery', 'ancient-chamber-established')),
(@ant_world_book_id, 3, 'the-soul-seed', 'The Soul Seed', 'The ancient chamber opens and the dying Soul Seed awakens, giving the protagonist a brief soul-level vision without fully explaining the ancient king.', JSON_ARRAY('ancient chamber opens', 'dying Soul Seed awakens', 'energy wave touches every ant present', 'protagonist sees an enormous crowned wounded ancient ant', 'the vision disappears before full explanation'), JSON_ARRAY('the Soul Seed exists and is alive enough to awaken', 'the protagonist has a soul-level connection to the ancient vision'), JSON_ARRAY('symbols and scent connection', 'rescue and emotional bond', 'violent survival and injury', 'confusion, displacement, and uncanny contact'), JSON_ARRAY('Soul Seed awakens, the crowned wounded ancient ant vision occurs, and Chapter 3 ends without complete explanation'), JSON_ARRAY('complete King legacy truth', 'Royal Soul Resonance name', 'tournament truth', 'Great War truth', 'sanctuary truth', 'final enemy'), JSON_ARRAY('chamber-opening', 'route-reason-for-entry', 'soul-seed-pulse', 'energy-wave', 'ancient-ant-vision', 'chapter-end')),
(@ant_world_book_id, 4, 'the-ants-path', 'The Ant''s Path', 'Growth begins to reflect behavior rather than chosen class.', JSON_ARRAY('first blood survived'), JSON_ARRAY('The Grand Insect Tournament is announced'), JSON_ARRAY('warrior-like', 'scout-like', 'mage-like', 'support', 'commander', 'observer', 'unknown path'), JSON_ARRAY('Grand Insect Tournament announced'), JSON_ARRAY('tournament soul energy', 'Great War full truth'), JSON_ARRAY('training', 'body-change', 'relationships', 'announcement')),
(@ant_world_book_id, 5, 'the-queens-secret', 'The Queen''s Secret', 'The Queen reveals the tournament is older and stranger than public history.', JSON_ARRAY('tournament announced'), JSON_ARRAY('the first tournament involved the Ant King'), JSON_ARRAY('investigation', 'Queen confidence', 'secrecy'), JSON_ARRAY('Ant Empire selected to participate'), JSON_ARRAY('soul-energy mechanism', 'sanctuary truth'), JSON_ARRAY('private-audience', 'old-tournament', 'selection')),
(@ant_world_book_id, 6, 'the-seven-territories', 'The Seven Territories', 'The story expands beyond the colony into Eldara politics.', JSON_ARRAY('Ant Empire selected'), JSON_ARRAY('another powerful insect recognizes the unusual soul'), JSON_ARRAY('exploration', 'alliances', 'rivalries', 'trade', 'combat', 'secret discovery'), JSON_ARRAY('soul recognized beyond the colony'), JSON_ARRAY('sanctuary truth', 'final enemy'), JSON_ARRAY('territory-map', 'first-contact', 'recognition')),
(@ant_world_book_id, 7, 'the-first-champion', 'The First Champion', 'The Ant representative is chosen through reputation and consequence.', JSON_ARRAY('soul recognized beyond the colony'), JSON_ARRAY('representation matters more than raw strength'), JSON_ARRAY('champion', 'supporter', 'challenger', 'manipulator', 'refusal'), JSON_ARRAY('Ant representative enters the tournament'), JSON_ARRAY('soul-energy mechanism details'), JSON_ARRAY('selection-begins', 'politics', 'entry')),
(@ant_world_book_id, 8, 'the-grand-tournament', 'The Grand Tournament', 'Young representatives gather; rivalry, alliance, and hidden machinery appear.', JSON_ARRAY('Ant representative entered'), JSON_ARRAY('Tournament collects soul energy'), JSON_ARRAY('combat', 'strategy', 'survival', 'magic', 'teamwork', 'rivalry'), JSON_ARRAY('Tournament connects to the coming Great War'), JSON_ARRAY('Ant King sanctuary truth', 'final enemy'), JSON_ARRAY('arrival', 'events', 'soul-energy-clue', 'war-connection')),
(@ant_world_book_id, 9, 'the-tournaments-truth', 'The Tournament''s Truth', 'The player investigates ancient history and chooses what to do with truth.', JSON_ARRAY('soul energy discovered'), JSON_ARRAY('The Ant King disappeared intentionally'), JSON_ARRAY('expose truth', 'hide truth', 'use truth', 'tell Queen', 'tell faction'), JSON_ARRAY('someone within Ant Empire betrays the colony'), JSON_ARRAY('complete sanctuary truth', 'final enemy'), JSON_ARRAY('investigation', 'history-fragments', 'choice', 'betrayal-sign')),
(@ant_world_book_id, 10, 'the-betrayal', 'The Betrayal', 'Internal attack makes relationships and ignored consequences matter.', JSON_ARRAY('betrayal sign established'), JSON_ARRAY('Ant Empire loses something meaningful'), JSON_ARRAY('defense', 'loss', 'rescue', 'retaliation', 'political fracture'), JSON_ARRAY('Insect civilizations enter the Great War'), JSON_ARRAY('sanctuary truth', 'final evolution logic'), JSON_ARRAY('attack', 'relationship-payoff', 'loss', 'war-declared')),
(@ant_world_book_id, 11, 'the-great-war', 'The Great War', 'The world enters war; player role emerges from development and relationships.', JSON_ARRAY('Great War started'), JSON_ARRAY('Ant King sanctuary location discovered'), JSON_ARRAY('soldier', 'commander', 'scout', 'mage', 'strategist', 'assassin', 'diplomat'), JSON_ARRAY('Ant Empire discovers ancient sanctuary location'), JSON_ARRAY('sanctuary truth', 'final enemy'), JSON_ARRAY('warfront', 'role-payoff', 'sanctuary-location')),
(@ant_world_book_id, 12, 'the-forgotten-king', 'The Forgotten King', 'The sanctuary reveals the truth of the vanished King and the player''s soul.', JSON_ARRAY('sanctuary location known'), JSON_ARRAY('player is the beginning of the King''s next existence while remaining themselves'), JSON_ARRAY('legacy choice', 'soul resonance', 'identity integration'), JSON_ARRAY('player accepts or rejects what the legacy means'), JSON_ARRAY('final enemy identity until earned', 'final evolution result'), JSON_ARRAY('sanctuary-entry', 'truth', 'legacy-choice')),
(@ant_world_book_id, 13, 'the-last-evolution', 'The Last Evolution', 'Highest story evolution is resolved from the entire life, not a dropdown.', JSON_ARRAY('legacy choice made'), JSON_ARRAY('final evolution emerges from the run'), JSON_ARRAY('king', 'ultimate-warrior', 'ancient-mage', 'evolutionary-intelligence', 'guardian', 'predator', 'unknown', 'hidden'), JSON_ARRAY('final enemy reveals itself'), JSON_ARRAY('final confrontation outcome'), JSON_ARRAY('reckoning', 'evolution', 'enemy-reveal')),
(@ant_world_book_id, 14, 'the-final-war', 'The Final War', 'All threads converge and death remains possible.', JSON_ARRAY('final enemy revealed'), JSON_ARRAY('allies and enemies are consequences of the run'), JSON_ARRAY('war resolution', 'sacrifice', 'death', 'victory conditions'), JSON_ARRAY('survive the final war or die with special ending'), JSON_ARRAY('final ending result'), JSON_ARRAY('allies-gather', 'battle', 'war-outcome')),
(@ant_world_book_id, 15, 'the-last-ant', 'The Last Ant', 'Final confrontation and meaning of existence are resolved from aggregate state.', JSON_ARRAY('final war survived'), JSON_ARRAY('the player defines the King''s new legacy'), JSON_ARRAY('The King', 'The Savior', 'The Peacemaker', 'The Strongest', 'The Usurper', 'The Last Ant', 'The Fall', 'The Transcendent', 'Hidden Endings'), JSON_ARRAY('ending resolver selects a satisfied ending'), JSON_ARRAY(), JSON_ARRAY('confrontation', 'choice', 'ending'))
ON DUPLICATE KEY UPDATE
  slug = VALUES(slug),
  title = VALUES(title),
  purpose = VALUES(purpose),
  required_canon_json = VALUES(required_canon_json),
  major_revelations_json = VALUES(major_revelations_json),
  possible_developments_json = VALUES(possible_developments_json),
  end_conditions_json = VALUES(end_conditions_json),
  blocked_revelations_json = VALUES(blocked_revelations_json),
  scene_guidance_json = VALUES(scene_guidance_json);
