SET @ant_world_book_id = (SELECT book_id FROM deep_saga_books WHERE slug = 'ant-world' LIMIT 1);

UPDATE deep_saga_books
SET
  title = 'The Ant World: The King''s Soul',
  description = 'A human soul reincarnates as an ant in Eldara and discovers the First King, Royal Soul Resonance, the hidden purpose of the Grand Insect Tournament, and the Hollow Sovereign behind the ancient soul system.'
WHERE book_id = @ant_world_book_id;

UPDATE deep_saga_story_guides
SET canon_json = JSON_OBJECT(
  'world', 'Eldara',
  'engineLaw', JSON_ARRAY('AI = GAME MASTER', 'STORY GUIDE = CANON', 'PLAYER = PROTAGONIST', 'ENGINE = REALITY'),
  'startingState', JSON_OBJECT('species', 'Ant', 'lifeStage', 'Larva', 'level', 1, 'location', 'Ant Nursery', 'humanMemoriesRetained', true),
  'majorCivilizations', JSON_ARRAY('Ants', 'Spiders', 'Bees', 'Beetles', 'Scorpions', 'Grasshoppers', 'Butterflies', 'Flies', 'Mosquitoes'),
  'centralCanon', JSON_ARRAY('The protagonist is not simply the Ant King reincarnated', 'The protagonist is the beginning of the Ant King''s next existence while remaining themselves', 'Royal Soul Resonance exists', 'The tournament secretly harvests soul energy', 'The Great War was manipulated', 'The sanctuary exists', 'The Hollow Sovereign exists', 'Chapter 15 resolves the central conflict'),
  'antagonist', JSON_OBJECT('name', 'The Hollow Sovereign', 'truth', 'An ancient consciousness that consumes, redirects, and combines soul energy because it cannot naturally create life'),
  'freePlay', JSON_ARRAY('relationships', 'routes', 'deaths', 'survival', 'abilities', 'alliances', 'mistakes', 'chapter approach', 'revelation experience', 'final evolution expression'),
  'blockedEarlySpoilers', JSON_ARRAY('full Ant King revelation', 'Royal Soul Resonance name', 'tournament soul-energy revelation', 'Great War manipulation', 'sanctuary truth', 'Hollow Sovereign identity', 'final evolution logic')
)
WHERE book_id = @ant_world_book_id;

INSERT INTO deep_saga_chapters
  (book_id, chapter_number, slug, title, purpose, required_canon_json, major_revelations_json, possible_developments_json, end_conditions_json, blocked_revelations_json, scene_guidance_json)
VALUES
(@ant_world_book_id, 1, 'the-smallest-soul', 'The Smallest Soul', 'Introduce reincarnation, the ant body, human identity, colony life, pheromone communication, helplessness, the first mystery, and the idea that something is unusual about the protagonist.', JSON_ARRAY('player awakens as an ant larva inside the Ant Nursery', 'human death memory is retained but incomplete', 'pheromones begin functioning as communication', 'an unusual pheromone signature appears within or around the colony', 'something is observing, searching, or approaching the colony'), JSON_ARRAY('the protagonist is alive', 'the protagonist is an ant', 'human consciousness remains intact', 'the colony communicates through chemical signals', 'something unusual is occurring around the colony', 'the protagonist is unusually perceptive or unusual in some way'), JSON_ARRAY('investigate strange scent', 'focus on survival', 'communicate with workers', 'hide', 'attempt escape', 'investigate human memories', 'attach to an NPC', 'behave aggressively', 'behave peacefully', 'ignore mystery', 'accidentally encounter information'), JSON_ARRAY('disturbance occurs within the colony', 'the protagonist becomes aware that something is searching, observing, or approaching', 'the protagonist survives the first crisis', 'the nursery is no longer completely safe'), JSON_ARRAY('Ant King truth', 'Royal Soul Resonance name', 'tournament truth', 'Great War truth', 'Hollow Sovereign identity', 'Soul Seed identity', 'sanctuary truth', 'final evolution logic'), JSON_ARRAY('awakening', 'ant-body', 'human-memory', 'pheromone-language', 'unusual-scent', 'first-disturbance')),
(@ant_world_book_id, 2, 'under-the-earth', 'Under the Earth', 'Expand beyond the nursery into colony hierarchy, worker life, soldiers, territory, ancient structures, serious danger, and forgotten colony history.', JSON_ARRAY('the protagonist interacts with a larger portion of the colony', 'workers, soldiers, scouts, nurses, elders, or other characters may appear organically', 'an old section contains evidence of something deliberately sealed', 'the seal predates the current generation', 'an ancient royal symbol connected to the vanished Ant King appears'), JSON_ARRAY('the Ant Empire has forgotten important history', 'the vanished Ant King was more important than current history suggests', 'something ancient exists beneath the colony', 'the protagonist has an unusual reaction to something connected to that history'), JSON_ARRAY('exploration', 'relationships', 'combat', 'helping workers', 'following scent', 'getting lost', 'being rescued', 'investigating markings', 'following NPCs', 'accidental forbidden-area entry'), JSON_ARRAY('the ancient seal becomes disturbed', 'something beneath the colony responds', 'the protagonist has their first undeniable supernatural reaction'), JSON_ARRAY('Soul Seed full nature', 'Ant King full truth', 'Royal Soul Resonance name', 'tournament truth', 'Great War truth', 'Hollow Sovereign identity', 'sanctuary truth', 'final evolution logic'), JSON_ARRAY('larger-colony', 'hierarchy', 'sealed-section', 'royal-symbol', 'supernatural-reaction')),
(@ant_world_book_id, 3, 'the-soul-below', 'The Soul Below', 'Introduce the first direct connection between the protagonist and the vanished Ant King.', JSON_ARRAY('ancient chamber beneath the colony opens or partially awakens', 'the Soul Seed is found as an ancient soul mechanism', 'the Soul Seed reacts to the protagonist', 'the protagonist sees a partial vision of the Ant King'), JSON_ARRAY('the King existed', 'the King discovered something dangerous', 'the King deliberately hid something', 'the protagonist is connected to him', 'their reincarnation is not an accident'), JSON_ARRAY('symbols and scent connection', 'rescue and emotional bond', 'violent survival and injury', 'confusion, displacement, and uncanny contact'), JSON_ARRAY('Soul Seed awakens', 'the protagonist experiences powerful resonance', 'soul and King remnant overlap briefly', 'the chamber falls silent', 'the protagonist survives', 'the world above does not understand what happened'), JSON_ARRAY('complete King truth', 'Royal Soul Resonance name', 'tournament truth', 'Great War truth', 'Hollow Sovereign identity', 'sanctuary truth', 'final evolution logic'), JSON_ARRAY('ancient-chamber', 'Soul-Seed', 'partial-awakening', 'Ant-King-vision', 'reincarnation-not-accident')),
(@ant_world_book_id, 4, 'the-king-who-disappeared', 'The King Who Disappeared', 'Begin investigating the Ant King''s history through records, elders, royal structures, or surviving traditions.', JSON_ARRAY('the official story says the Ant King disappeared during crisis', 'deeper evidence shows the King intentionally vanished after discovering the soul-energy system', 'the King suspected someone inside insect civilizations helped the system continue', 'the King left hidden safeguards'), JSON_ARRAY('the Ant King was not defeated in a normal war', 'he chose to disappear', 'he left hidden safeguards', 'the protagonist is one of those safeguards'), JSON_ARRAY('records', 'elders', 'royal structures', 'oral tradition', 'dangerous clues', 'relationship access', 'enemy interference'), JSON_ARRAY('evidence connects the King''s disappearance to events beyond the Ant Empire', 'the mystery expands from why did I become an ant to what happened to the Ant King'), JSON_ARRAY('Royal Soul Resonance full nature', 'tournament soul-energy revelation', 'Great War manipulation', 'Hollow Sovereign identity', 'sanctuary truth', 'final evolution logic'), JSON_ARRAY('historical-records', 'vanished-king', 'safeguards', 'beyond-ant-empire')),
(@ant_world_book_id, 5, 'the-grand-insect-tournament', 'The Grand Insect Tournament', 'Introduce the tournament publicly as competition, prestige, resources, influence, and danger while hiding its true function.', JSON_ARRAY('the Grand Insect Tournament is announced or becomes relevant', 'it appears to offer honor, territory, prestige, resources, political influence, and rewards', 'the protagonist may participate, refuse, investigate, support indirectly, or avoid it', 'the true purpose remains hidden'), JSON_ARRAY('the tournament matters to the wider world', 'something is wrong beneath the public competition', 'a powerful contestant experiences an unnatural soul disturbance'), JSON_ARRAY('participation', 'refusal', 'investigation', 'indirect involvement', 'supporting another contestant', 'political connection', 'avoidance'), JSON_ARRAY('the protagonist senses an unnatural soul disturbance', 'the tournament continues'), JSON_ARRAY('tournament soul-energy function', 'Great War manipulation', 'Hollow Sovereign identity', 'sanctuary truth', 'final evolution logic'), JSON_ARRAY('announcement', 'public-glory', 'contestants', 'soul-disturbance', 'suspicion')),
(@ant_world_book_id, 6, 'the-soul-that-should-not-exist', 'The Soul That Should Not Exist', 'Reveal the protagonist''s connection to Royal Soul Resonance without making them merely the King reborn.', JSON_ARRAY('the protagonist experiences a stronger resonance', 'ancient mechanisms respond', 'certain beings may recognize something unusual', 'the name Royal Soul Resonance is learned'), JSON_ARRAY('Royal Soul Resonance is not simply a magical ability', 'it connects the protagonist to royal soul architecture created by the Ant King', 'the protagonist is becoming something new', 'the King''s next existence begins through them while they remain themselves'), JSON_ARRAY('mechanism reaction', 'recognition by powerful beings', 'fear', 'training', 'hiding', 'political pressure', 'personal identity conflict'), JSON_ARRAY('someone or something realizes the King''s soul has returned', 'the protagonist is no longer invisible to the forces that caused the King to disappear'), JSON_ARRAY('Great War full manipulation', 'Hollow Sovereign identity', 'sanctuary truth', 'final evolution logic'), JSON_ARRAY('stronger-resonance', 'name-revealed', 'royal-soul-architecture', 'new-target')),
(@ant_world_book_id, 7, 'the-war-of-many-wings', 'The War of Many Wings', 'Expand conflict from personal mystery into wider civilizational war and manipulation.', JSON_ARRAY('tensions between insect civilizations escalate', 'ants, spiders, beetles, bees, scorpions, grasshoppers, and others move toward conflict', 'evidence shows the conflict is not entirely natural'), JSON_ARRAY('the Great War was not simply caused by hatred between species', 'ancient forces amplified existing conflicts', 'the purpose was unstable soul energy'), JSON_ARRAY('diplomacy', 'battlefield survival', 'espionage', 'rescue', 'alliance building', 'betrayal', 'investigation', 'faction pressure'), JSON_ARRAY('the Great War begins or becomes unavoidable', 'the world changes permanently', 'the protagonist can no longer return to simple colony life'), JSON_ARRAY('tournament mechanism full truth', 'Hollow Sovereign identity', 'sanctuary truth', 'final evolution logic'), JSON_ARRAY('rising-tension', 'civilizations', 'manipulation-clues', 'war-begins')),
(@ant_world_book_id, 8, 'the-broken-kingdom', 'The Broken Kingdom', 'Show war consequences and make prior relationships matter.', JSON_ARRAY('the Ant Empire suffers', 'colonies fall', 'alliances break', 'important characters may die', 'others may betray one another', 'relationship history changes available allies and losses'), JSON_ARRAY('the Ant King predicted this war', 'he left instructions and safeguards throughout Eldara', 'the protagonist is following one without initially realizing it'), JSON_ARRAY('allies from relationships', 'isolation consequences', 'loss', 'betrayal', 'defense', 'retreat', 'rescue', 'leadership', 'survival'), JSON_ARRAY('the protagonist discovers a path toward the legendary sanctuary'), JSON_ARRAY('complete sanctuary truth', 'Hollow Sovereign identity', 'final evolution logic'), JSON_ARRAY('war-loss', 'relationship-payoff', 'hidden-instructions', 'path-to-sanctuary')),
(@ant_world_book_id, 9, 'the-sanctuary', 'The Sanctuary', 'Reveal the King''s sanctuary and the first deep truth of his soul fracture.', JSON_ARRAY('the protagonist reaches the sanctuary', 'the sanctuary protects souls from the ancient system', 'the King''s final plan becomes clearer'), JSON_ARRAY('the Ant King deliberately fractured his soul', 'one fragment became the Soul Seed', 'one fragment remained hidden', 'one fragment became the foundation of the protagonist''s reincarnation', 'the protagonist is not the King but the continuation of his existence'), JSON_ARRAY('trial', 'memory', 'relationship confrontation', 'soul pressure', 'choice to accept or reject legacy', 'sanctuary defense'), JSON_ARRAY('the sanctuary reveals the King did not plan to resurrect himself', 'he created a chance for something new to emerge'), JSON_ARRAY('tournament mechanism full truth', 'Hollow Sovereign identity', 'final evolution logic'), JSON_ARRAY('sanctuary-entry', 'soul-protection', 'fractured-soul', 'continuation-not-replacement')),
(@ant_world_book_id, 10, 'the-truth-of-the-tournament', 'The Truth of the Tournament', 'Reveal the tournament''s real function as soul-energy harvesting.', JSON_ARRAY('the protagonist learns the Grand Insect Tournament is part of an ancient collection system', 'competition, ambition, fear, combat, death, and victory generate soul energy', 'that energy is collected and redirected'), JSON_ARRAY('the tournament is not the true enemy', 'it is a machine used by something older', 'insect civilizations have been manipulated into maintaining it'), JSON_ARRAY('expose truth', 'hide truth', 'sabotage', 'rescue contestants', 'political maneuvering', 'direct confrontation', 'spiritual investigation'), JSON_ARRAY('the protagonist realizes stopping the tournament alone will not solve the problem', 'something deeper controls the system'), JSON_ARRAY('Hollow Sovereign identity', 'final evolution logic'), JSON_ARRAY('harvesting-revealed', 'system-machine', 'deeper-controller')),
(@ant_world_book_id, 11, 'the-hollow-sovereign', 'The Hollow Sovereign', 'Reveal the true enemy behind the ancient manipulation.', JSON_ARRAY('the protagonist encounters the truth behind the ancient manipulation', 'the entity is known as the Hollow Sovereign', 'it cannot create true life', 'it consumes soul energy and manipulates civilizations to produce it', 'the Ant King discovered this'), JSON_ARRAY('the Hollow Sovereign wanted the Ant King''s Royal Soul Resonance', 'the King refused', 'the protagonist now possesses the beginning of that same resonance', 'the protagonist becomes the new target'), JSON_ARRAY('vision', 'record', 'direct contact', 'battle', 'possession attempt', 'soul pressure', 'ally warning', 'enemy revelation'), JSON_ARRAY('the Hollow Sovereign becomes aware the protagonist has reached awakening', 'the protagonist can no longer remain hidden'), JSON_ARRAY('King''s last memory full truth', 'final evolution logic'), JSON_ARRAY('true-enemy', 'cannot-create-life', 'perfect-vessel', 'new-target')),
(@ant_world_book_id, 12, 'the-kings-last-memory', 'The King''s Last Memory', 'Reveal the complete history of the Ant King and why the protagonist must become something new.', JSON_ARRAY('the protagonist accesses the deepest remaining memory of the King', 'the King discovered the soul-energy system', 'he could not destroy it without killing millions of connected souls', 'he fractured his soul, created the sanctuary, hid knowledge, and prepared for a future existence'), JSON_ARRAY('the protagonist was never created to become the Ant King', 'they were created to have the opportunity to become something the King could not become', 'the whole journey now matters'), JSON_ARRAY('memory trial', 'identity crisis', 'relationship reflection', 'moral reckoning', 'legacy acceptance', 'legacy rejection'), JSON_ARRAY('the protagonist understands their choices, relationships, failures, evolution, morality, and actions shape what the King''s continuation becomes'), JSON_ARRAY('final evolution result', 'final confrontation outcome'), JSON_ARRAY('deep-memory', 'system-cannot-be-destroyed-simply', 'future-existence', 'journey-matters')),
(@ant_world_book_id, 13, 'the-last-war', 'The Last War', 'Bring all major forces into conflict and reach the heart of the ancient soul mechanism.', JSON_ARRAY('the Hollow Sovereign begins activating the ancient soul system', 'remaining civilizations are forced into final conflict', 'allies, enemies, factions, and battlefield circumstances come from the established run', 'the protagonist reaches the heart of the soul mechanism'), JSON_ARRAY('everything converges', 'the Hollow Sovereign attempts to use Royal Soul Resonance to complete its vessel'), JSON_ARRAY('army with allies', 'lonely infiltration', 'defense', 'sacrifice', 'betrayal', 'diplomacy', 'battlefield command', 'soul resistance'), JSON_ARRAY('the final confrontation begins'), JSON_ARRAY('final evolution result', 'final ending result'), JSON_ARRAY('system-activation', 'final-conflict', 'heart-of-mechanism', 'vessel-attempt')),
(@ant_world_book_id, 14, 'the-soul-of-the-king', 'The Soul of the King', 'Resolve the protagonist''s relationship with the Ant King before the ending.', JSON_ARRAY('the protagonist reaches the deepest point of the soul mechanism', 'the Ant King''s remaining consciousness appears', 'the protagonist confronts the question Am I you', 'the answer is no', 'the King gives no command'), JSON_ARRAY('the protagonist is themselves', 'the King''s existence continues through them', 'Royal Soul Resonance was never intended to create another King', 'the final decision belongs entirely to the protagonist'), JSON_ARRAY('acceptance', 'rejection', 'forgiveness', 'anger', 'mercy', 'ambition', 'sacrifice', 'transformation'), JSON_ARRAY('the protagonist decides what their soul has become', 'that decision determines final evolution and ending'), JSON_ARRAY('final ending result'), JSON_ARRAY('king-consciousness', 'identity-answer', 'no-command', 'final-decision')),
(@ant_world_book_id, 15, 'the-kings-soul', 'The King''s Soul', 'Final confrontation and resolution of the Hollow Sovereign, Royal Soul Resonance, final evolution, and Eldara''s future.', JSON_ARRAY('the protagonist confronts the Hollow Sovereign', 'the final battle is influenced by the complete run', 'final form emerges from accumulated development and choices', 'the Hollow Sovereign''s fate is resolved', 'the ancient soul system is changed, destroyed, sealed, or transformed', 'the Great War ends or enters a new era'), JSON_ARRAY('the protagonist is no longer simply an ordinary ant', 'they are the culmination of human identity, ant existence, personal choices, Royal Soul Resonance, and the legacy of the Ant King', 'their final relationship with the King''s legacy is established'), JSON_ARRAY('defeat', 'transform', 'seal', 'replace', 'redeem', 'sacrifice', 'rule', 'reject power', 'transcend', 'die with meaning'), JSON_ARRAY('the central conflict is resolved according to the path created during the run', 'Eldara begins rebuilding or enters its new era', 'the story ends with the protagonist''s final state established'), JSON_ARRAY(), JSON_ARRAY('final-confrontation', 'final-evolution', 'Hollow-Sovereign-fate', 'Eldara-future', 'ending'))
ON DUPLICATE KEY UPDATE
  slug = VALUES(slug),
  title = VALUES(title),
  purpose = VALUES(purpose),
  required_canon_json = VALUES(required_canon_json),
  major_revelations_json = VALUES(major_revelations_json),
  possible_developments_json = VALUES(possible_developments_json),
  end_conditions_json = VALUES(end_conditions_json),
  blocked_revelations_json = VALUES(blocked_revelations_json),
  scene_guidance_json = VALUES(scene_guidance_json);
