const worldBible = [
  {
    number: 1,
    name: 'Cradlewood Threshold',
    kind: 'Living Forest Gate',
    theme: 'first survival, monster instinct, and the fear of being newly reborn',
    difficulty: 1,
    boss: 'Mawroot, the Hunger Under Bark',
  },
  {
    number: 2,
    name: 'Glassweb Hollows',
    kind: 'Underground Silk Kingdom',
    theme: 'web politics, predatory intelligence, and body horror evolution',
    difficulty: 2,
    boss: 'Silk-Mother Velratha',
  },
  {
    number: 3,
    name: 'Mire-Crown Principality',
    kind: 'Sunken Monster Court',
    theme: 'goblin nobles, swamp oaths, and the price of civilization',
    difficulty: 3,
    boss: 'Prince Gorrik of the Rot-Crown',
  },
  {
    number: 4,
    name: 'Ashbell Academy Ruins',
    kind: 'Collapsed Magic School',
    theme: 'lost lessons, cursed teachers, and spellcraft with consequences',
    difficulty: 4,
    boss: 'Headmaster Cindervane',
  },
  {
    number: 5,
    name: 'Moon-Eaten Bazaar',
    kind: 'Night Market Between Worlds',
    theme: 'contracts, cursed items, merchants, and impossible bargains',
    difficulty: 5,
    boss: 'The Debt Saint of Lantern Row',
  },
  {
    number: 6,
    name: 'Iron Orchard Dominion',
    kind: 'Mechanical War Garden',
    theme: 'living machines, fruit of metal, and soldiers grown from roots',
    difficulty: 6,
    boss: 'General Pomegranate-9',
  },
  {
    number: 7,
    name: 'Saintless Cathedral',
    kind: 'Godless Holy Citadel',
    theme: 'faith without gods, angels without mercy, and holy lies',
    difficulty: 7,
    boss: 'Seraphel, the Empty Halo',
  },
  {
    number: 8,
    name: 'Demon-Seal Archipelago',
    kind: 'Chain of Prison Islands',
    theme: 'sealed demon clans, ocean trials, and inherited curses',
    difficulty: 8,
    boss: 'Varrox Tidebound, Chain-Eater',
  },
  {
    number: 9,
    name: 'Chronicle Labyrinth',
    kind: 'Library That Rewrites Time',
    theme: 'memory, reincarnation records, erased companions, and false endings',
    difficulty: 9,
    boss: 'Archivist Null, Keeper of Unlived Lives',
  },
  {
    number: 10,
    name: 'Throne of the Previous Self',
    kind: 'Legacy Realm',
    theme: 'all lives remembered, all victories judged, and the strongest former hero waiting',
    difficulty: 10,
    boss: 'The Eternal Guardian',
  },
]

module.exports = { worldBible }
